#!/bin/bash

cd /tmp/rom # Depends on where source got synced

find .repo/ -delete

# Normal build steps
. build/envsetup.sh
lunch dot_sakura-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make api-stubs-docs
make system-api-stubs-docs
make test-api-stubs-docs
make bacon -j16
