#!/bin/bash

mkdir -p /tmp/rom
cd /tmp/rom

git config --global user.name GeoPD
git config --global user.email geoemmanuelpd2001@gmail.com

export rom=evo

rom_one(){
 repo init --no-repo-verify -u git://github.com/DotOS/manifest.git -b dot11 -g default,-device,-mips,-darwin,-notdefault
 repo sync --no-tags --no-clone-bundle --current-branch --force-sync --optimized-fetch -j12
 git clone https://$TOKEN@github.com/geopd/device_xiaomi_sakura_TEST.git -b dot-11 device/xiaomi/sakura
 git clone https://$TOKEN@github.com/geopd/vendor_xiaomi_sakura_TEST.git -b lineage-18.0 vendor/xiaomi
 . build/envsetup.sh && lunch dot_sakura-userdebug
}

rom_two(){
 repo init --no-repo-verify -u https://github.com/Evolution-X/manifest -b elle -g default,-device,-mips,-darwin,-notdefault
 repo sync --no-tags --no-clone-bundle --current-branch --force-sync --optimized-fetch -j12
 git clone https://$TOKEN@github.com/geopd/device_xiaomi_sakura_TEST.git -b elle device/xiaomi/sakura
 git clone https://$TOKEN@github.com/geopd/vendor_xiaomi_sakura_TEST.git -b lineage-18.0 vendor/xiaomi
 . build/envsetup.sh && lunch evolution_sakura-userdebug
}

git clone https://$TOKEN@github.com/geopd/kernel_xiaomi_msm8953 -b beta-4.9-Q kernel/xiaomi/msm8953 
git clone https://github.com/geopd/vendor_custom_prebuilts -b master vendor/custom/prebuilts
git clone https://github.com/mvaisakh/gcc-arm64.git -b gcc-master prebuilts/gcc/linux-x86/aarch64/aarch64-elf

case "$rom" in
 "dot") rom_one
    ;;
 "evo") rom_two
    ;;
 *) echo "Invalid option!"
    exit 1
    ;;
esac

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G && ccache -o compression=true && ccache -z
make api-stubs-docs && make system-api-stubs-docs && make test-api-stubs-docs

case "$rom" in
 "dot") make bacon -j16
    ;;
 "evo") mka bacon -j16
    ;;
 *) echo "Invalid option!"
    exit 1
    ;;
esac
