#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc

cd /tmp # Where to download cccahe
mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
time rclone copy brrbrr:/ccache/ccache.tar.gz /tmp -P
time tar xf ccache.tar.gz
find ccache.tar.gz -delete
