#!/bin/bash

mkdir -p /tmp/rom
cd /tmp/rom

git config --global user.name GeoPD
git config --global user.email geoemmanuelpd2001@gmail.com

# Build environment
git clone https://github.com/akhilnarang/scripts
bash scripts/setup/android_build_env.sh && rm -rf scripts

# Repo init and sync
repo init --no-repo-verify --depth=1 -u git://github.com/DotOS/manifest.git -b dot11 -g default,-device,-mips,-darwin,-notdefault
repo sync --no-tags --no-clone-bundle --current-branch --force-sync --optimized-fetch -j10

# clone needed repos
git clone https://$TOKEN@github.com/geopd/device_xiaomi_sakura_TEST.git -b dot-11 device/xiaomi/sakura
git clone --depth=1 https://$TOKEN@github.com/geopd/vendor_xiaomi_sakura_TEST.git -b lineage-18.0 vendor/xiaomi
git clone --depth=1 https://github.com/darkhz/revvz_sakura -b beta-4.9-Q kernel/xiaomi/msm8953 
git clone --depth=1 https://github.com/geopd/vendor_custom_prebuilts -b master vendor/custom/prebuilts
git clone --depth=1 https://github.com/mvaisakh/gcc-arm64.git -b gcc-master prebuilts/gcc/linux-x86/aarch64/aarch64-elf
